### ISSUE TITLE
which dataset you guys used for solubility predition? 

### ISSUE THREAD

**Issue by kexul** [CanisW/TF3P#1]
Is that ESOL? If so, the result seems not so promising  compared to some 2D neural fingerprint learned by graph networks.

**Comment by CanisW** [comment]
We just wanna show its compatability here. 
Another noteworthy point is that 2D neural fps you mentioned were trained directly on the ESOL dataset. TF3P's performance may be better if further fine-tuned for ESOL.
(Sorry for late responce, and the revised paper will be updated on arxiv soon. Thanks for interets.)
