### ISSUE TITLE
error during model execussion

### ISSUE THREAD

**Issue by thegodone** [CanisW/TF3P#4]
/tmp/TF3P/model/networks.py:86: 

UserWarning: 
Using a target size (torch.Size([27, 2, 50, 50, 50])) 
that is different to the input size (torch.Size([9, 2, 50, 50, 50])). 
This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
 loss = weight * F.mse_loss(ff, reconstructions)

RuntimeError: The size of tensor a (9) must match the size of tensor b (27) at non-singleton dimension 0
Closing remaining open 

when we set Batchsize to 9 we have not the correct number of sample per batch (27).

can you fix this bug please ?

I try with a batchsize of 5 (while v,fp,ff are correctly set to 5) and we got 25 in the reconstruction mask batch dimension:

torch.Size([5, 1, 2, 50, 50, 50])
torch.Size([5, 864, 4])
torch.Size([5, 1, 864, 4, 1])
torch.Size([1, 166, 864, 8, 4])
mask: torch.Size([5, 1, 166, 1])
decoder: torch.Size([25, 2, 50, 50, 50])
v shape: torch.Size([5, 166, 8]) , fp shape: torch.Size([5, 1, 166]) , ff shape: torch.Size([5, 2, 50, 50, 50]) ,recon shape: torch.Size([25, 2, 50, 50, 50])
----------------------------------------------------------------------------------------------------
/fwd/TF3P/model/networks.py:91: UserWarning: Using a target size (torch.Size([25, 2, 50, 50, 50])) that is different to the input size (torch.Size([5, 2, 50, 50, 50])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = weight * F.mse_loss(ff, reconstructions)

**Comment by CanisW** [comment]
maybe due to the wrong dim of mask? it should be (batch_size, 166, 1).
